name: Release

on:
  push:
    branches: ["master"]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
